// *******************************
// ** code generated by coml
// *******************************

#include "../../src/cmn/service.hpp"
#include "../../src/cui/api.hpp"
#include "../../src/cui/pen.hpp"
#include "../../src/tcatlib/api.hpp"
#include <iostream>

class test_image : public cui::iImage {
public:
   virtual void render()
   {
      tcat::typePtr<cmn::serviceManager> svcMan;
      auto& pn = svcMan->demand<pen::object>();

      pn.str() << "" << "bleh" << "" << "bleh" << "+- value #1 [xxx] -+" << std::endl;
   }

   virtual cui::pnt demandPnt(const std::string& id) { throw 3.14; }
};

class test_str1_ctl : public cui::stringControl {
protected:
   virtual void formatText1(std::ostream& o)
   {
   }
   virtual void formatText2(std::ostream& o)
   {
   }
   virtual void formatText3(std::ostream& o)
   {
   }
   virtual void formatText4(std::ostream& o)
   {
   }
};

class test_screen : public cui::basicScreen {
protected:
   test_image m_image;
   test_str1_ctl m_str1;

public:
   test_screen()
   {
      publishObject("",m_image);
      publishObject("str1",m_str1);
   }

   virtual void render()
   {
      m_image.render();
      m_str1.initialize(cui::pnt(14,1),3,1);
   }
};
